### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by milan9527** [aws-samples/amazon-memorydb-for-redis-samples#10]
1. After running ragmm_app.py, below error occurs. 
An error occurred while connecting to Redis: Error -2 connecting to clusterurl:6379. Name or service not known.

All environment variables are set:
export BWB_ENDPOINT_URL=https://bedrock-runtime.us-east-1.amazonaws.com
export MemoryDB_ENDPOINT_URL=redis://clustercfg.ping.0uiite.memorydb.us-east-1.amazonaws.com:6379
export BWB_PROFILE_NAME=bedrock
export BWB_REGION_NAME=us-east-1

It seems cluster url is not resolved correctly. I modify ragmm_lib.py to hard code REDIS_URL and redis host then it works fine.

2. Above error disappears but another failure occurs.
NameError: name 'rds' is not defined

Modify ragmm_lib.py to use redis_client instead of rds.

def perform_query(query):
    #results = rds.similarity_search(query)
    results = redis_client.similarity_search(query)
    return results

My login: pingaws@

**Comment by LakshmiPeri23** [comment]
The code is updated to read from environment variable. could you try again
